version: "3.8"

services:
  db_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn db_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  business_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn business_service:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  client_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn client_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - APP_TOKEN=${APP_TOKEN}
